name: Build Rust Release on Tagged Master Push

on:
  push:
    tags:
      - 'v*'                   # Match tags starting with 'v'
    
jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/v') && github.ref_type == 'tag' && github.ref_name == contains(github.ref_name, 'v')  # Only build on tags
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build release
        run: cargo build --release
