name: Build Rust Release on x.x.x Tag Push

on:
  push:
    tags:
      - '*.*.*'   # Matches tags like 1.2.3, 10.0.1, etc.

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - run: cargo build --release --target=x86_64-pc-windows-msvc
    
    # Setup 7zip
    - uses: milliewalky/setup-7-zip@v2
    
    # Pack binary as 7z archive
    - run: 7z a -t7z ipchanger.7z ./target/x86_64-pc-windows-msvc/release/ipchanger.exe
    
    # Create GitHub release and upload artifact
    - uses: ncipollo/release-action@v1
      with:
        artifacts: ipchanger.7z
        token: ${{ secrets.GITHUB_TOKEN }}
